CREATE DATABASE if NOT EXISTS resgate_rs;
USE resgate_rs;

CREATE TABLE centro_distribuicao(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	endereco VARCHAR(300) NOT NULL,
	cep VARCHAR(9) NOT NULL,
	
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE abrigos ( 
	id INT AUTO_INCREMENT PRIMARY KEY, 
	nome VARCHAR(50) NOT NULL, 
	endereco VARCHAR(100) NOT NULL, 
	cep VARCHAR(10) NOT NULL, 
	cidade VARCHAR(20) NOT NULL, 
	responsavel VARCHAR(50) NOT NULL, 
	telefone VARCHAR(20) NOT NULL, 
	email VARCHAR(50) NOT NULL, 
	capacidade INT NOT NULL, 
	ocupacao INT NOT NULL 
	
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE armazem (
	id INT AUTO_INCREMENT,
	centro_distribuicao_id INT NULL,
	abrigo_id INT NULL,
	
	PRIMARY KEY (id),
	FOREIGN KEY (centro_distribuicao_id) REFERENCES centro_distribuicao(id) ON DELETE CASCADE,
	FOREIGN KEY (abrigo_id) REFERENCES abrigos(id) ON DELETE CASCADE
		
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE produtos (
	id INT  NOT NULL AUTO_INCREMENT,
	categoria ENUM('ALIMENTO', 'HIGIENE', 'ROUPA') NOT NULL,
	item ENUM('ARROZ', 'FEIJAO', 'LEITE', 'SABONETE', 'ESCOVA_DE_DENTES', 'PASTA_DE_DENTES', 'ABSORVENTE', 'AGASALHO', 'CAMISA') NOT NULL,
	sexo ENUM('F', 'M'),
	tamanho ENUM('INFANTIL', 'PP', 'P', 'M', 'G', 'GG'),
	quantidade INT NOT NULL,
	armazem_id INT NOT NULL,
	
	PRIMARY KEY (id),
	FOREIGN KEY (armazem_id) REFERENCES armazem(id) ON DELETE CASCADE
	
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4; 


CREATE TABLE ordem_pedidos(
	id INT NOT NULL AUTO_INCREMENT,
	centro_distribuicao_id INT NOT NULL,
	abrigo_id INT NOT NULL,
	categoria ENUM('ALIMENTO', 'HIGIENE', 'ROUPA') NOT NULL,
	item ENUM('ARROZ', 'FEIJAO', 'LEITE', 'SABONETE', 'ESCOVA_DE_DENTES', 'PASTA_DE_DENTES', 'ABSORVENTE', 'AGASALHO', 'CAMISA') NOT NULL,
	quantidade INT NOT NULL,
	status ENUM('ACEITO', 'RECUSADO', 'PENDENTE') NOT NULL,
	motivo VARCHAR(255) NULL,
	
	PRIMARY KEY (id),
	FOREIGN KEY (centro_distribuicao_id) REFERENCES centro_distribuicao(id) ON DELETE CASCADE,
	FOREIGN KEY (abrigo_id) REFERENCES abrigos(id) ON DELETE CASCADE	
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;